name: Deploy Gatsby site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Build storybook
        run: |
          yarn install
          yarn build-storybook

      - name: Move files to storybook folder
        run: |
          mkdir -p storybook
          mv storybook-static/* storybook/

      - name: Deploy to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.STORYBOOK_TOKEN }}
          publish_dir: ./storybook
          publish_branch: gh-page
          destination_dir: storybook